#!/usr/bin/env python
# -*- coding: utf-8 -*- 
training_data = []
training_data.append({"class":"sad","sentence": "I'm feeling down about work lately."})
training_data.append({"class":"sad","sentence": "Tom's upset about his boss. He's too hard on him!"})
training_data.append({"class":"sad","sentence": "I'm sad about the situation at work."})
training_data.append({"class":"sad","sentence": "Peter is out of sorts today. Ask him tomorrow."})
training_data.append({"class":"sad","sentence": "the staff does not feel well about the changes at work."})
training_data.append({"class":"sad","sentence": "Jack is feeling blue about his relationship with his girlfriend."})
training_data.append({"class":"sad","sentence": "Kelly is in the dumps about her horrible job."})
training_data.append({"class":"sad","sentence": "Keith feels down in the mouth about his relationship."})
training_data.append({"class":"sad","sentence": "i went through a breakup"})
training_data.append({"class":"sad","sentence": "I was so depressed when my pet rabbit died."})
training_data.append({"class":"sad","sentence": "Her words made me feel really unhappy."})
training_data.append({"class":"sad","sentence": "That TV show made me weepy."})
training_data.append({"class":"sad","sentence": "I’m feeling a little low at the moment."})
training_data.append({"class":"sad","sentence": "I feel down at the moment, I think I should talk to a counsellor."})
training_data.append({"class":"sad","sentence": "Down in the dumps"})
training_data.append({"class":"sad","sentence": "At the end of my tethe"})
training_data.append({"class":"sad","sentence": "Grief-stricken"})
training_data.append({"class":"sad","sentence": "A face like a wet weekend"})
training_data.append({"class":"sad","sentence": "Crying my eyes out"})
training_data.append({"class":"sad","sentence": "My heart sank"})
training_data.append({"class":"sad","sentence": ""})
#training_data.append({"class":"sad","sentence": ""})
#training_data.append({"class":"sad","sentence": ""})

training_data.append({"class":"angery","sentence": " I don’t think that’s very clever!"})
training_data.append({"class":"angery","sentence": "Are you trying to be funny?"})
training_data.append({"class":"angery","sentence": "You wouldn’t dare!"})
training_data.append({"class":"angery","sentence": "Don’t be silly!"})
training_data.append({"class":"angery","sentence": "How dare you say that!"})
training_data.append({"class":"angery","sentence": "Hang it!"})
training_data.append({"class":"angery","sentence": "Get lost!"})
training_data.append({"class":"angery","sentence": "Enough is good!"})
training_data.append({"class":"angery","sentence": "That’s the limit!"})
training_data.append({"class":"angery","sentence": "This is too much!"})
training_data.append({"class":"angery","sentence": "Rubbish!"})
training_data.append({"class":"angery","sentence": " Good riddance!"})
training_data.append({"class":"angery","sentence": " And what next?"})
training_data.append({"class":"angery","sentence": "I won’t swallow that!"})
training_data.append({"class":"angery","sentence": " I’m warning you!"})
training_data.append({"class":"angery","sentence": "Just you wait!"})
training_data.append({"class":"angery","sentence": " Get out of my way!"})
training_data.append({"class":"angery","sentence": "That’s the last straw!"})
training_data.append({"class":"angery","sentence": "Mind your own business!"})
training_data.append({"class":"angery","sentence": "It’s none of your business!"})
training_data.append({"class":"angery","sentence": "Shame on you!"})
training_data.append({"class":"angery","sentence": "It makes me see red!"})
training_data.append({"class":"angery","sentence": "I have enough of that boy!"})
training_data.append({"class":"angery","sentence": " I won’t have it!"})
training_data.append({"class":"angery","sentence": "Why are so angry with her?"})
training_data.append({"class":"angery","sentence": " Who do you take me for?"})
training_data.append({"class":"angery","sentence": "For God’s sake, leave me alone!"})
training_data.append({"class":"angery","sentence": "I’m fed up with his lies."})
training_data.append({"class":"angery","sentence": "I’m fed up with your interrupting me all the time."})
training_data.append({"class":"angery","sentence": "Why the hell didn’t you wait for me?"})
training_data.append({"class":"angery","sentence": " I won’t stand being treated like that."})
training_data.append({"class":"angery","sentence": " I can’t stand it any longer!"})
training_data.append({"class":"angery","sentence": "I’ve heard as much as I can hear!"})
training_data.append({"class":"angery","sentence": " I can’t put up with him!"})
training_data.append({"class":"angery","sentence": " I won’t put up with that!"})
training_data.append({"class":"angery","sentence": "I’m sick of all this!"})
training_data.append({"class":"angery","sentence": " That serves you right!"})
training_data.append({"class":"angery","sentence": "I’m sick and tired of telling you!"})
training_data.append({"class":"angery","sentence": "I’m tired of them!"})
training_data.append({"class":"angery","sentence": "She’s cross with you because you have disobeyed"})
training_data.append({"class":"angery","sentence": "He’s furious with them."})
training_data.append({"class":"angery","sentence": " What on earth have you been doing?"})
training_data.append({"class":"angery","sentence": "What has that got to do with it?"})
training_data.append({"class":"angery","sentence": " That gets on my nerves!"})
training_data.append({"class":"angery","sentence": " How on earth can you live in such a filthy place?"})
training_data.append({"class":"angery","sentence": " There is no reason why I should stay here."})
training_data.append({"class":"angery","sentence": "What irritates me most is that nobody believes me."})
training_data.append({"class":"angery","sentence": " I won’t tolerate living among them."})
training_data.append({"class":"angery","sentence": " i will kill you"})


training_data.append({"class":"happy","sentence": "I was happy when my nan came to stay."})
training_data.append({"class":"happy","sentence": "I felt ecstatic when I passed my exam."})
training_data.append({"class":"happy","sentence": "I was overjoyed at the birth of my son."})
training_data.append({"class":"happy","sentence": "During the Christmas holidays I felt wonderfully merry."})
training_data.append({"class":"happy","sentence": "When I sign the lease on my new apartment, I’m going to jump for joy!"})
training_data.append({"class":"happy","sentence": "The food at the five-star restaurant is awesome!"})
training_data.append({"class":"happy","sentence": "When I graduated from college, I was on cloud nine!"})
training_data.append({"class":"happy","sentence": "The owner of the company is really generous with vacation time."})
training_data.append({"class":"happy","sentence": " I’m honored to accept this position in the company and will work hard to make the team proud!"})
training_data.append({"class":"happy","sentence": "After she said yes to his proposal, he was so happy that he was grinning from ear to ear for weeks after."})
training_data.append({"class":"happy","sentence": "The cake we had for the holiday was homemade, so it was extraordinarily delicious."})
training_data.append({"class":"happy","sentence": "Once we lit the fire in the furnace, we all sat down with a cup of chocolate and I was a happy camper."})
training_data.append({"class":"happy","sentence": "The handmade furniture was perfect for our home and fit just as we expected!"})
training_data.append({"class":"happy","sentence": "I’m happy to see you back on your feet only a week after your surgery!"})
training_data.append({"class":"happy","sentence": "Her success in the last three years brought her into the role as a director of the department."})
training_data.append({"class":"happy","sentence": "All the compliments from my last project were like music to my ears."})
training_data.append({"class":"happy","sentence": "After her last movie, she became famous in the United States and the U.K."})
training_data.append({"class":"happy","sentence": "Traveling across the world makes me happy as a clam."})
training_data.append({"class":"happy","sentence": " I admire people who are generous and kind."})
training_data.append({"class":"happy","sentence": "The team’s jaws dropped after finishing a three-year project."})
training_data.append({"class":"happy","sentence": "Traveling is so exciting that it motivates me to work hard."})
training_data.append({"class":"happy","sentence": "My brother becomes friends with everyone he meets because his personality is larger than life!"})
training_data.append({"class":"happy","sentence": "It’s courageous when people to stand up for what they believe "})
training_data.append({"class":"happy","sentence": "I got my college acceptance letter this afternoon, it’s the best day ever!"})
training_data.append({"class":"happy","sentence": "On cloud nine"})
training_data.append({"class":"happy","sentence": "Flying high"})
training_data.append({"class":"happy","sentence": "Full of the joys of spring"})
training_data.append({"class":"happy","sentence": "Grin from ear-to-ear"})
training_data.append({"class":"happy","sentence": "Grin like a Cheshire cat"})
training_data.append({"class":"happy","sentence": "Happy camper"})
training_data.append({"class":"happy","sentence": "Happy as Larry"})
training_data.append({"class":"happy","sentence": "i want to kiss my girlfriend"})




training_data.append({"class":"fear","sentence": "It was such a terrifying ordeal. I’m glad that it’s over."})
training_data.append({"class":"fear","sentence": "I watched a horror movie yesterday. Some of the scenes and the sound effects were so frightening that they sent shivers down my spine."})
training_data.append({"class":"fear","sentence": "I can’t watch horror films. They give me goose bumps."})
training_data.append({"class":"fear","sentence": "If something makes the hairs on the back of your neck stand up, they scare you."})
training_data.append({"class":"fear","sentence": "I get scared really easily."})
training_data.append({"class":"fear","sentence": "I’m afraid of the dark."})
training_data.append({"class":"fear","sentence": " can’t watch horror films. They scare me."})
training_data.append({"class":"fear","sentence": "I had a terrifying experience last week."})
training_data.append({"class":"fear","sentence": "I get scared when I’m at home all by myself."})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})

print ("%s sentences of training data" % len(training_data))
